### ISSUE TITLE
節末問題 4.5.1 の解答：グラフBの次数

### ISSUE THREAD

**Issue by miy4** [E869120/math-algorithm-book#2]
## 該当の箇所

- [節末問題 4.5 の解答](https://github.com/E869120/math-algorithm-book/blob/main/editorial/chap4-5/chap4-5.pdf)

## 説明

節末問題 4.5.1 の解答の中で、グラフBの頂点の次数は`次数=1`と記載されています。
該当の頂点は4本の辺と接続しているため、次数は4になるのではないかと思ったのですが、いかがでしょうか？
もし自分の思い違いでしたら、ヒントを頂けるとうれしいです。

**Comment by E869120** [comment]
次数=4 が正解ですので、修正しました。
ご指摘ありがとうございます。
